spring:
  ai:
    openai:
      api-key: SECRET_OPENAI_API_KEY
      chat-completions-url: https://api.openai.com/v1/chat/completions
      use-streaming: false
      chat:
        options:
          model: gpt-4o
  data:
    mongodb:
      uri: >-
        mongodb://admin:admin@localhost:27017/chat_log?authSource=admin
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssafyhome?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: yaguhang@gmail.com
    password: SECRET_MAIL_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
app:
  cors:
    allowedOrigins:
      - http://localhost:3000
      - http://localhost:8080
      - http://localhost:5173
  auth:
    tokenSecret: SECRET_JWT_SECRET
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - http://localhost:5173/oauth2/redirect
      - https://yaguhang.kro.kr:7443/oauth2/redirect
      - https://yaguhang.kro.kr:8443/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.ai.openai: DEBUG
    org.springframework.ai.chat: DEBUG
    org.springframework.web.client.RestClient: TRACE
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
API:
#  key: eq3Do1yF57fqENuUSWwSlibvbOtmwRIgJLStRfGz%2BK1CqY6rKvCGH7vfXUZmXgmv0XWVGa7kGz7W0Cnz5EKA4w%3D%3D
  key: SECRET_EXTERNAL_API_KEY