cloud:
  aws:
    credentials:
      access-key: SECRET_AWS_ACCESS_KEY
      secret-key: SECRET_AWS_SECRET_KEY
    s3:
      bucket: yaguhang-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false